<!-- <template>
  <div ref="container"></div>
</template>

<script lang="ts" setup>
import * as vg from "@uwdata/vgplot";
import { onMounted, ref } from "vue";

let container = ref();

onMounted(async () => {
  // configure the coordinator to use DuckDB-WASM
  // creates a new database instance running in-browser
  const wasm = await vg.wasmConnector();
  vg.coordinator().databaseConnector(wasm);

  // load data into the database
  // executes a query generated by the loadCSV helper
  vg.coordinator().exec(
    vg.loadCSV(
      "stocks",
      "https://raw.githubusercontent.com/uwdata/mosaic/main/data/stocks.csv"
    )
  );

  // create an area chart, returned as an HTML element
  // you can subsequently add this to your webpage
  const chart = vg.plot(
    vg.areaY(vg.from("stocks"), { x: "Date", y: "Volume", fill: "Symbol" })
  );

  container.value.appendChild(chart);
});
</script> -->

<template>
  <div ref="container"></div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import * as vg from "@uwdata/vgplot";

let container = ref();

const wasm = await vg.wasmConnector();
vg.coordinator().databaseConnector(wasm);

onMounted(async () => {
  await vg.coordinator().exec(
    vg.loadParquet(
      "aapl",
      "https://uwdata.github.io/mosaic/data/stocks.parquet",
      {
        where: "Symbol = 'AAPL'",
      }
    )
  );

  let chart = vg.plot(vg.line(vg.from("aapl"), { x: "Date", y: "Close" }));

  container.value.appendChild(chart);
});
</script>
