<template>
  <div ref="container"></div>
</template>

<script lang="ts" setup>
import * as vg from "@uwdata/vgplot";
import { onMounted, ref } from "vue";

let container = ref();

onMounted(async () => {
  // configure the coordinator to use DuckDB-WASM
  // creates a new database instance running in-browser
  const wasm = await vg.wasmConnector();
  vg.coordinator().databaseConnector(wasm);

  // load data into the database
  // executes a query generated by the loadCSV helper
  vg.coordinator().exec(
    vg.loadCSV(
      "stocks",
      "https://raw.githubusercontent.com/uwdata/mosaic/main/data/stocks.csv"
    )
  );

  // create an area chart, returned as an HTML element
  // you can subsequently add this to your webpage
  const chart = vg.plot(vg.areaY(vg.from("stocks"), { x: "Date", y: "Close" }));

  container.value.appendChild(chart);
});
</script>
