<script lang="ts" setup>
import * as vg from "@uwdata/vgplot";
import { onMounted } from 'vue'

onMounted(async () => {
    // configure the coordinator to use DuckDB-WASM
    // creates a new database instance running in-browser
    const wasm = await vg.wasmConnector();
    vg.coordinator().databaseConnector(wasm);

    // load data into the database
    // executes a query generated by the loadCSV helper
    vg.coordinator().exec(vg.loadCSV("stocks", "https://raw.githubusercontent.com/uwdata/mosaic/main/data/stocks.csv"));

    // create an area chart, returned as an HTML element
    // you can subsequently add this to your webpage
    const chart = vg.plot(
        vg.areaY(vg.from("stocks"), { x: "Date", y: "Close" })
    );
})
</script>
